export const GET_LIVE_URL = "/live-monitoring/scan-timeline"
export const GET_UNIQUE_DOMAINS_COUNT = "/live-monitoring/unique-domains-count"
export const GET_TAGGING_DISTRIBUTION = "/live-monitoring/tagging-distribution"
export const GET_CURRENT_SCAN = "/live-monitoring/current-scan-progress"
export const GET_URL_PROCESSES = "/live-monitoring/url-processes"